version: '3.8'

services:
  backstage:
    image: roadiehq/community-backstage-image:latest
    ports:
      - "7000:7000"  # Backstage UI at http://localhost:7000
    environment:
      - GITHUB_TOKEN=""  # Replace with your token
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage_user
      - POSTGRES_PASSWORD=backstage_password
      - POSTGRES_DB=backstage_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backstage-net

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=backstage_user
      - POSTGRES_PASSWORD=backstage_password
      - POSTGRES_DB=backstage_db
    ports:
      - "5432:5432"  # Optional: Expose PostgreSQL port locally
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backstage_user -d backstage_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backstage-net

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"  # pgAdmin UI at http://localhost:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - backstage-net

networks:
  backstage-net:
    driver: bridge

volumes:
  postgres-data: